/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ct;
import java.sql.*;
import javax.swing.JOptionPane;


public class OKS extends javax.swing.JFrame {

 public OKS OKS;
 public Connection cn;
 public Statement st;
    public OKS() {
        initComponents();
        try{ 
           Class.forName("com.mysql.jdbc.Driver");
           cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ctlab","root","");
           st=cn.createStatement();
           JOptionPane.showMessageDialog(null,"Connected");
       }
       catch(Exception e)
       {
       JOptionPane.showMessageDialog(null,"not Connected");
    
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Conf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel1.setText("Success");

        Conf.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        Conf.setText("Confirm Booking");
        Conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Conf, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(97, 97, 97)
                .addComponent(Conf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfActionPerformed
        // TODO add your handling code here:
        try{
         String sql="select amount from item where item='Samsung J7'";
         ResultSet rss=st.executeQuery(sql);
         rss.first(); 
         int a=Integer.parseInt(rss.getString("amount"));
                
                String sqlq="SELECT amount from user WHERE ID='1'";
                ResultSet rs=st.executeQuery(sqlq);
                rs.first();
                int b=Integer.parseInt(rs.getString("amount"));
               if(a <= b){
                    int c=b-a;
                    String sqlw="SELECT Balance FROM merchant WHERE ID='101'";
                    ResultSet rsss=st.executeQuery(sqlw);
                    rsss.first();
                    int d=Integer.parseInt(rsss.getString("Balance"));
                    int e=d+a;
                    st.executeUpdate("UPDATE user SET amount='"+c+"'");
                    st.executeUpdate("UPDATE merchant SET Balance='"+e+"'");
                    JOptionPane.showMessageDialog(null,"Purchased Sucessfully");
                   Bills bi=new Bills();
                   bi.setVisible(true);
                   JOptionPane.showMessageDialog(null,"Rs 17000 is credited to Merchant's account");
                }else{
                  JOptionPane.showMessageDialog(null,"Amount Insufficient");
                }
            }catch (Exception e) {
        JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_ConfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OKS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Conf;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
