/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ct;

/**
 *
 * 
 */
public class Purchase extends javax.swing.JFrame {

    /**
     * Creates new form Purchase
     */
    public Purchase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Mobbut = new javax.swing.JButton();
        Appbut = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Shopping");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(254, 39, 120, 25);

        Mobbut.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        Mobbut.setForeground(new java.awt.Color(255, 0, 0));
        Mobbut.setText("Mobiles");
        Mobbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobbutActionPerformed(evt);
            }
        });
        getContentPane().add(Mobbut);
        Mobbut.setBounds(30, 40, 137, 33);

        Appbut.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        Appbut.setForeground(new java.awt.Color(255, 51, 51));
        Appbut.setText("Appliances");
        Appbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppbutActionPerformed(evt);
            }
        });
        getContentPane().add(Appbut);
        Appbut.setBounds(420, 40, 183, 33);

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(460, 90, 13, 2);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(270, 100, 10, 10);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ct/Shop.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 640, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MobbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobbutActionPerformed
        View v=new View();
        v.setVisible(true); 
    }//GEN-LAST:event_MobbutActionPerformed

    private void AppbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppbutActionPerformed
        View1 v=new View1();
        v.setVisible(true);
    }//GEN-LAST:event_AppbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Appbut;
    private javax.swing.JButton Mobbut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
